Repository awell-health/hosted-pages, pull requests merged in 2023-07, with the labels that each got.

#124 Add russian locale
  next-i18next.config.js
  public/locales/et/common.json
  public/locales/ru/common.json
Labels: enhancement, i18n

#125 chore(release): 0.0.52
  package.json
Labels: skip-changelog

#126 fix(i18n): fix invalid url translation
  src/services/authentication/AuthenticationProvider.tsx
Labels: bug, i18n

#131 Use polling for hosted session updates
  src/components/Message/Message.tsx
  src/hooks/useHostedSession/useHostedSession.ts
  src/types/generated/fragment-types.ts
  src/types/generated/types-orchestration.tsx
Labels: echoes/intent: unblock-customers

#133 Add Support to traditional forms
  package.json
  public/locales/en/common.json
  public/locales/et/common.json
  public/locales/fr/common.json
  public/locales/nl/common.json
  public/locales/ro/common.json
  public/locales/ru/common.json
  src/components/Form/Form.tsx
  src/hooks/useSessionActivities/graphql/Activity.graphql
  src/types/generated/types-orchestration.tsx
  yarn.lock
Labels: echoes/intent: stabilise-be-hospital-segment

#135 chore(sentry): update to version 7.59.3
  package.json
Labels: dependencies

#138 fix: manually update apollo cache on activity completion
  src/components/Activities/Activities.tsx
  src/hooks/activityNavigation/ActivityContext.ts
  src/hooks/activityNavigation/ActivityProvider.tsx
  src/hooks/useCompleteExtensionActivity/useCompleteExtensionActivity.ts
  src/hooks/useManuallyUpdateActvitiesCache/index.ts
  src/hooks/useManuallyUpdateActvitiesCache/types.ts
  src/hooks/useManuallyUpdateActvitiesCache/useManuallyUpdateActivitiesCache.ts
  src/hooks/useMessage/useMessage.ts
  src/hooks/useSubmitChecklist/useSubmitChecklist.ts
  src/hooks/useSubmitForm/useSubmitForm.ts
Labels: bug, refactor, echoes/intent: unblock-customers, echoes/impediment: technical-debt

#141 fix: remove session activity updated event as it is not needed
  src/hooks/activityNavigation/ActivityProvider.tsx
  src/hooks/useSessionActivities/useSessionActivities.ts
Labels: echoes/intent: unblock-customers

#143 feat: add autoProgress param to the conversational form from branding…
  package.json
  src/components/Form/Form.tsx
  src/hooks/useHostedSession/graphql/getHostedSession.graphql
  src/types/generated/types-orchestration.tsx
  yarn.lock
Labels: echoes/effort: XS, echoes/intent: stabilise-be-hospital-segment
