Repository awell-health/hosted-pages, pull requests merged in 2023-11, with the labels that each got.

#169 chore(sentry): include request and response headers and request bodies
  pages/index.tsx
  sentry.client.config.js
  sentry.server.config.js
  src/components/AuthGuard.tsx
  src/components/Form/Form.tsx
  src/services/ErrorReporter/addSentryBreadcrumb.ts
  src/services/ErrorReporter/index.ts
  src/services/ErrorReporter/masker.ts
  src/services/authentication/AuthenticationProvider.tsx
Labels: echoes/intent: throughput

#170 Bump version to 0.0.73
  package.json
  yarn.lock
Labels: skip-changelog, dependencies, echoes/intent: throughput

#175 Bump ui library to 0.1.30
  package.json
  yarn.lock
Labels: echoes/intent: unblock, echoes/impediment: technical-debt, echoes/effort: XS

#176 Bump version to 0.0.74
  package.json
Labels: echoes/intent: unblock, echoes/impediment: technical-debt, echoes/effort: XS

#181 ci: echoeshq deployment status
  .github/workflows/publish-release.yml
  scripts/fail_release.sh
  scripts/publish_release.sh
Labels: echoes/intent: throughput, echoes/effort: S

#182 ci(echoes): add option to run from multiple actions in workflow trigger
  .github/workflows/publish-release.yml
Labels: echoes/intent: throughput, echoes/effort: XS

#183 ci(platform): publish release
  .github/workflows/publish-release.yml
  scripts/fail_release.sh
  scripts/publish_release.sh
Labels: echoes/intent: throughput, echoes/effort: XS

#186 bump version 0.0.76
  package.json
Labels: skip-changelog, echoes/intent: throughput

#188 Error page fix
  package.json
  pages/api/startHostedActivitySessionViaHostedPagesLink/[hostedPagesLinkId].ts
  pages/api/startHostedPathwaySessionFromLink/[hostedPagesLinkId].ts
  pages/index.tsx
  src/components/StartHostedActivitySessionFlow/StartHostedActivitySessionFlow.tsx
  src/components/StartHostedPathwaySessionFlow/StartHostedPathwaySessionFlow.tsx
  src/services/ErrorReporter/addSentryBreadcrumb.ts
  types/StartHostedActivitySessionPayload.ts
Labels: bug, echoes/intent: fast-track
