Repository awell-health/hosted-pages, pull requests merged in 2023-12, with the labels that each got.

#192 V1C-317-fix-redirect-on-ahp
  src/components/StartHostedPathwaySessionFlow/StartHostedPathwaySessionFlow.tsx
Labels: echoes/intent: unblock, echoes/effort: XS

#193 V1C-23 deps(ui-library): replace with new ui-library package and update imports
  package.json
  pages/_app.tsx
  pages/c/[hostedPagesLinkId].tsx
  pages/index.tsx
  pages/l/[hostedPagesLinkId].tsx
  pages/preview.tsx
  src/components/Checklist/Checklist.tsx
  src/components/CloseHostedSessionModal/CloseHostedSessionModal.tsx
  src/components/ErrorPage/ErrorPage.tsx
  src/components/Extension/CalDotComExtension/BookAppointmentAction.tsx
  src/components/Extension/CalDotComExtension/types.ts
  src/components/Extension/CloudinaryExtension/actions/UploadFilesAction/UploadFilesAction.tsx
  src/components/Extension/CloudinaryExtension/actions/UploadSingleFileAction/UploadSingleFileAction.tsx
  src/components/Extension/DocuSignExtension/actions/EmbeddedSigningAction/FinishedMessage.tsx
  src/components/Extension/DocuSignExtension/actions/EmbeddedSigningAction/SigningProcess.tsx
  src/components/Extension/DropboxSignExtension/actions/EmbeddedSigningAction/EmbeddedSigningAction.tsx
  src/components/Form/Form.tsx
  src/components/LoadingPage/LoadingPage.tsx
  src/components/Message/Message.tsx
  src/hooks/useForm/graphql/Question.graphql
  src/types/generated/types-orchestration.tsx
  yarn.lock
Labels: dependencies, echoes/intent: fast-track, echoes/impediment: dependencies

#194 deps(ui-lib): bump to 0.1.35
  package.json
  yarn.lock
Labels: dependencies, echoes/intent: throughput
