Repository awell-health/hosted-pages, pull requests merged in 2023-10, with the labels that each got.

#158 chore(dependencies): bump @awell_health/ui-library from 0.1.25 to 0.1.26
  package.json
  yarn.lock
Labels: dependencies

#159 TP-215 fix(activities): sort activities by date when updating via subscription
  src/hooks/useSessionActivities/useSessionActivities.ts
Labels: bug, echoes/intent: unblock

#163 Update package.json
  package.json
Labels: skip-changelog

#167 chore(translations): French
  public/locales/fr/common.json
Labels: echoes/intent: fast-track, echoes/effort: XS

#168 Tp-345-create-browser-test-to-replicate-failure-to-complete-form
  src/services/graphql/apollo-client.ts
  yarn.lock
Labels: echoes/intent: throughput
