Repository awell-health/hosted-pages, pull requests merged in 2024-09, with the labels that each got.

#261 Identity check with DOB
  lib/index.ts
  lib/jwt-feature.ts
  pages/api/identity/verify.ts
  pages/api/startHostedActivitySessionViaHostedPagesLink/[hostedPagesLinkId].ts
  pages/api/startHostedPathwaySessionFromLink/[hostedPagesLinkId].ts
  public/locales/en/common.json
  src/components/Extension/Extension.tsx
  src/components/Extension/IdentityVerification/IdentityVerification.tsx
  src/components/Extension/IdentityVerification/actions/DobCheck/DobCheck.module.css
  src/components/Extension/IdentityVerification/actions/DobCheck/DobCheck.tsx
  src/components/Extension/IdentityVerification/actions/DobCheck/hooks/useDobCheck.tsx
  src/components/Extension/IdentityVerification/actions/DobCheck/index.tsx
  src/components/Extension/IdentityVerification/actions/DobCheck/types.ts
  src/components/Extension/IdentityVerification/actions/index.ts
  src/components/Extension/IdentityVerification/index.tsx
  src/components/Extension/IdentityVerification/types.ts
  src/components/Extension/types.ts
Labels: echoes/intent: fast-track, echoes/intent: bootcamp

#264 ET-217: copy schema + update ui-library
  package.json
  src/types/generated/fragment-types.ts
  src/types/generated/types-orchestration.tsx
  yarn.lock
Labels: echoes/intent: throughput

#265 ET-217: add label for invalid email format + bump ui-library
  package.json
  public/locales/de/common.json
  public/locales/en/common.json
  src/components/Form/Form.tsx
  yarn.lock
Labels: echoes/intent: throughput

#267 feat(extensions): add support for ReviewMedicationExtraction action
  next.config.js
  src/components/Extension/Extension.tsx
  src/components/Extension/ShellyExtension/ShellyExtension.tsx
  src/components/Extension/ShellyExtension/actions/ReviewMedicationExtraction/ReviewMedicationExtraction.module.css
  src/components/Extension/ShellyExtension/actions/ReviewMedicationExtraction/ReviewMedicationExtraction.tsx
  src/components/Extension/ShellyExtension/actions/ReviewMedicationExtraction/hooks/useReviewMedicationExtraction.tsx
  src/components/Extension/ShellyExtension/actions/ReviewMedicationExtraction/index.tsx
  src/components/Extension/ShellyExtension/actions/ReviewMedicationExtraction/types.ts
  src/components/Extension/ShellyExtension/actions/index.ts
  src/components/Extension/ShellyExtension/index.ts
  src/components/Extension/ShellyExtension/types.ts
  src/components/Extension/types.ts
Labels: echoes/intent: throughput

#266 feat(intake-scheduling): Updated to support provider preferences and additional onComplete datapoints
  package.json
  pages/api/sol/appointments.ts
  pages/api/sol/providers/[id]/availability.ts
  pages/api/sol/providers/index.ts
  src/components/Extension/PrivateExtensions/actions/IntakeScheduling/IntakeScheduling.tsx
  src/components/Extension/PrivateExtensions/actions/IntakeScheduling/api.service.ts
  src/components/Extension/PrivateExtensions/actions/IntakeScheduling/helpers/error.ts
  src/components/Extension/PrivateExtensions/actions/IntakeScheduling/hooks/useIntakeScheduling.tsx
  yarn.lock
Labels: echoes/intent: fast-track, echoes/intent: bootcamp

#268 bump(sol-scheduling): bump sol-scheduling to 0.2.8
  package.json
  yarn.lock
Labels: echoes/intent: fast-track, echoes/intent: bootcamp

#269 update Sol Scheduling
  package.json
  yarn.lock
Labels: echoes/intent: fast-track, echoes/intent: bootcamp

#270 release-sol-scheduling
  package.json
  yarn.lock
Labels: echoes/intent: fast-track, echoes/effort: XS

#271 chore(): codium pr agent
  .github/workflows/pr-agent.yml
Labels: enhancement, configuration changes, Review effort [1-5]: 2

#272 ET-250: finalize intake scheduling
  src/components/Extension/PrivateExtensions/actions/IntakeScheduling/IntakeScheduling.module.css
  src/components/Extension/PrivateExtensions/actions/IntakeScheduling/IntakeScheduling.tsx
  src/components/Extension/PrivateExtensions/actions/IntakeScheduling/hooks/useIntakeScheduling.tsx
Labels: enhancement, Review effort [1-5]: 2

#273 ET-252: use baseUrl from settings
  .env.sandbox.example
  package.json
  pages/api/sol/appointments.ts
  pages/api/sol/providers/[id]/availability.ts
  pages/api/sol/providers/index.ts
  pages/api/sol/utils.ts
  src/components/Extension/PrivateExtensions/actions/IntakeScheduling/IntakeScheduling.tsx
  src/components/Extension/PrivateExtensions/actions/IntakeScheduling/api.service.ts
  src/components/Extension/PrivateExtensions/actions/IntakeScheduling/types.ts
  yarn.lock
Labels: enhancement, Review effort [1-5]: 3

#275 chore(): implement sol-scheduling v14
  package.json
  pages/api/sol/providers/[id]/index.ts
  pages/api/sol/utils.ts
  src/components/Extension/PrivateExtensions/actions/IntakeScheduling/IntakeScheduling.tsx
  src/components/Extension/PrivateExtensions/actions/IntakeScheduling/api.service.ts
  yarn.lock
Labels: enhancement, dependencies, Review effort [1-5]: 3
