Repository awell-health/hosted-pages, pull requests merged in 2024-08, with the labels that each got.

#254 remove the location in sol api
  src/components/Extension/PrivateExtensions/actions/IntakeScheduling/api.service.ts
Labels: echoes/intent: fast-track

#257 fix(): date handling
  package.json
  src/components/Extension/PrivateExtensions/actions/IntakeScheduling/IntakeScheduling.tsx
  src/components/Extension/PrivateExtensions/actions/IntakeScheduling/api.service.ts
  src/components/Extension/PrivateExtensions/actions/IntakeScheduling/hooks/useIntakeScheduling.tsx
  yarn.lock
Labels: echoes/intent: unblock

#258 ET-128: stop polling when session is complete + change error message
  pages/index.tsx
  public/locales/en/common.json
  src/hooks/useHostedSession/useHostedSession.ts
Labels: echoes/impediment: technical-debt, echoes/intent: throughput

#260 ET-128: stop polling hostedSession query when session is complete
  src/hooks/useHostedSession/useHostedSession.ts
Labels: echoes/intent: unblock
