Repository awell-health/hosted-pages, pull requests merged in 2024-03, with the labels that each got.

#204 V1C-398 support for passing in patient identifier in hosted pages links
  pages/api/startHostedPathwaySessionFromLink/[hostedPagesLinkId].ts
  pages/c/[hostedPagesLinkId].tsx
  src/components/StartHostedPathwaySessionFlow/StartHostedPathwaySessionFlow.tsx
Labels: echoes/intent: throughput

#207 Fix identifier query params
  pages/api/startHostedPathwaySessionFromLink/[hostedPagesLinkId].ts
  pages/c/[hostedPagesLinkId].tsx
  src/components/StartHostedPathwaySessionFlow/StartHostedPathwaySessionFlow.tsx
Labels: bug, echoes/intent: fast-track, echoes/effort: XS

#211 fix(branding): fix zod error in custom branding from null branding settings
  src/hooks/useHostedSession/useHostedSession.ts
Labels: echoes/intent: unblock, echoes/effort: S

#212 refactor: simplify how to get/parse custom theme
  package.json
  src/hooks/useHostedSession/branding/customTheme.test.ts
  src/hooks/useHostedSession/branding/customTheme.ts
  src/hooks/useHostedSession/branding/index.ts
  src/hooks/useHostedSession/useHostedSession.ts
  yarn.lock
Labels: refactor, echoes/effort: XS

#214 TP-1300: Implement date validation in Hosted Pages
  package.json
  public/locales/de/common.json
  public/locales/en/common.json
  public/locales/es/common.json
  public/locales/et/common.json
  public/locales/fr/common.json
  public/locales/nl/common.json
  public/locales/ro/common.json
  public/locales/ru/common.json
  src/components/Form/Form.tsx
  src/hooks/useForm/graphql/Question.graphql
  src/types/generated/types-orchestration.tsx
  yarn.lock
Labels: echoes/intent: unblock
