Repository awell-health/hosted-pages, pull requests merged in 2024-11, with the labels that each got.

#298 feat: bump ui-library and update types
  package.json
  src/types/generated/fragment-types.ts
  src/types/generated/types-orchestration.tsx
  yarn.lock
Labels: echoes/impediment: technical-debt

#299 Et 331 new question type icd 10 classification
  package.json
  yarn.lock
Labels: echoes/impediment: technical-debt

#300 release-sol-scheduling-0.3.15
  package.json
  yarn.lock
Labels: Review effort [1-5]: 1

#301 release-sol-scheduling-0.3.16
  package.json
  yarn.lock
Labels: Review effort [1-5]: 1

#302 ET-365: fix warning loggings when API returns no providers or availabilities
  pages/api/sol/providers/[id]/availability.ts
  pages/api/sol/providers/index.ts
Labels: Review effort [1-5]: 2

#303 ET-364: add session and pathway ID to the logs for context
  pages/api/sol/appointments.ts
  pages/api/sol/providers/[id]/availability.ts
  pages/api/sol/providers/[id]/index.ts
  pages/api/sol/providers/index.ts
  src/components/Extension/PrivateExtensions/actions/IntakeScheduling/IntakeScheduling.tsx
  src/components/Extension/PrivateExtensions/actions/IntakeScheduling/api.service.ts
Labels: Review effort [1-5]: 3

#304 ET-379: bump ui-library and add translation for ICD question
  package.json
  public/locales/en/common.json
  public/locales/es/common.json
  public/locales/et/common.json
  public/locales/fr/common.json
  public/locales/nl/common.json
  public/locales/ro/common.json
  public/locales/ru/common.json
  src/components/Form/Form.tsx
  yarn.lock
Labels: echoes/intent: throughput, Review effort [1-5]: 2

#305 release-sol-scheduling-0.3.20
  package.json
  yarn.lock
Labels: Review effort [1-5]: 1

#306 release-sol-scheduling-0.3.21
  package.json
  yarn.lock
Labels: Review effort [1-5]: 1

#307 ET-454-release-sol-scheduling-0.3.22
  package.json
  yarn.lock
Labels: Review effort [1-5]: 1

#308 ET-454-release-sol-scheduling-0.3.23
  package.json
  yarn.lock
Labels: Review effort [1-5]: 1

#309 ET-454-release-sol-scheduling-0.3.24
  package.json
  yarn.lock
Labels: Review effort [1-5]: 1

#311 Bump ui library to v84
  package.json
Labels: Review effort [1-5]: 1

#312 ET-454-release-sol-scheduling-0.3.28
  package.json
  yarn.lock
Labels: Review effort [1-5]: 1

#313 ET-454-release-sol-scheduling-0.3.29
  package.json
  yarn.lock
Labels: Review effort [1-5]: 1
