Repository awell-health/hosted-pages, pull requests merged in 2024-12, with the labels that each got.

#314 ET-458: implement remote single select for requesting provider
  .env.sandbox.example
  pages/api/wp/lookup/auth.ts
  pages/api/wp/lookup/providers/[siteId]/index.ts
  pages/api/wp/settings.ts
  src/components/Extension/Extension.tsx
  src/components/Extension/PrivateExtensions/WP/RequestingProviderLookUp/RequestingProviderLookUp.module.css
  src/components/Extension/PrivateExtensions/WP/RequestingProviderLookUp/RequestingProviderLookUp.tsx
  src/components/Extension/PrivateExtensions/WP/RequestingProviderLookUp/hooks/useRequestingProviderLookUp.tsx
  src/components/Extension/PrivateExtensions/WP/RequestingProviderLookUp/index.tsx
  src/components/Extension/PrivateExtensions/WP/RequestingProviderLookUp/types.ts
  src/components/Extension/PrivateExtensions/WP/index.ts
  src/components/Extension/types.ts
Labels: Review effort [1-5]: 4

#319 ET-569: don't make q required if api fails
  src/components/Extension/PrivateExtensions/WP/RequestingProviderLookUp/RequestingProviderLookUp.tsx
Labels: Review effort [1-5]: 3

#320 Update ui library version 0.1.87
  package.json
  yarn.lock
Labels: Review effort [1-5]: 1

#321 ET-630: add support for Polish
  next-i18next.config.js
  public/locales/pl/common.json
Labels: Review effort [1-5]: 2

#324 ET-599: remote-single-select; allow more flexible data format
  src/components/Extension/CollectDataExtension/actions/RemoteSingleSelectAction/RemoteSingleSelectAction.test.ts
  src/components/Extension/CollectDataExtension/actions/RemoteSingleSelectAction/RemoteSingleSelectAction.tsx
  src/components/Extension/CollectDataExtension/actions/RemoteSingleSelectAction/hooks/useRemoteSingleSelectAction.tsx
  src/components/Extension/CollectDataExtension/actions/RemoteSingleSelectAction/types.ts
  src/hooks/useLogging/types.ts
Labels: Review effort [1-5]: 4
