Repository awell-health/hosted-pages, pull requests merged in 2024-01, with the labels that each got.

#195 feat: and onSessionActivityExpired subscription
  src/hooks/useSessionActivities/graphql/OnSessionActivityExpired.graphql
  src/hooks/useSessionActivities/types.ts
  src/hooks/useSessionActivities/useSessionActivities.ts
  src/types/generated/types-orchestration.tsx
Labels: echoes/intent: throughput

#196 feat(slider): implement new slider from ui-lib, add tests for slider-based forms
  package.json
  pages/index.tsx
  public/locales/en/common.json
  spec/mocks/index.ts
  spec/mocks/testFormFixture.ts
  src/components/Form/Form.spec.tsx
  src/components/Form/Form.tsx
  src/hooks/useHostedSession/useHostedSession.ts
  yarn.lock
Labels: test, refactor, echoes/intent: fast-track

#197 dep(ui-library): bump to 0.1.38
  package.json
  yarn.lock
Labels: dependencies

#199 V1C-363: Component for Remote Single Select Action
  package.json
  public/locales/en/common.json
  src/components/Extension/CollectDataExtension/CollectDataExtension.tsx
  src/components/Extension/CollectDataExtension/actions/RemoteSingleSelectAction/RemoteSingleSelectAction.tsx
  src/components/Extension/CollectDataExtension/actions/RemoteSingleSelectAction/hooks/useRemoteSingleSelectAction.tsx
  src/components/Extension/CollectDataExtension/actions/RemoteSingleSelectAction/index.tsx
  src/components/Extension/CollectDataExtension/actions/RemoteSingleSelectAction/remoteSingleSelectAction.module.css
  src/components/Extension/CollectDataExtension/actions/index.ts
  src/components/Extension/CollectDataExtension/index.tsx
  src/components/Extension/CollectDataExtension/types.ts
  src/components/Extension/Extension.tsx
  src/components/Extension/FormsortExtension/actions/CompleteFlowAction/CompleteFlowAction.tsx
  src/components/Extension/types.ts
  src/hooks/useEvaluateFormRules/useEvaluateFormRules.ts
  yarn.lock
Labels: enhancement, dependencies, echoes/intent: unblock, echoes/impediment: dependencies

#200 Fix type to search
  package.json
  public/locales/en/common.json
Labels: i18n, echoes/intent: fast-track

#201 Add support to value_string on questions
  package.json
  spec/mocks/testFormFixture.ts
  src/components/Form/Form.tsx
  src/hooks/useForm/graphql/Question.graphql
  src/types/generated/fragment-types.ts
  src/types/generated/types-orchestration.tsx
  yarn.lock
Labels: echoes/intent: throughput

#202 bump ui-library to 0.1.43
  package.json
Labels: echoes/intent: unblock
