Repository awell-health/hosted-pages, pull requests merged in 2024-06, with the labels that each got.

#240 Fix form submitting event
  src/components/Form/Form.tsx
  src/hooks/useLogging/types.ts
  src/hooks/useSubmitForm/useSubmitForm.ts
Labels: echoes/intent: throughput

#241 Add more metadata to Hosted Session logs and include logs for checklists
  src/hooks/useHostedSession/graphql/getHostedSession.graphql
  src/hooks/useHostedSession/useHostedSession.ts
  src/hooks/useLogging/types.ts
  src/hooks/useLogging/useLogging.ts
  src/hooks/useSessionActivities/graphql/Activity.graphql
  src/hooks/useSubmitChecklist/useSubmitChecklist.ts
  src/types/generated/fragment-types.ts
  src/types/generated/types-orchestration.tsx
Labels: echoes/intent: throughput

#247 TP-1570: add granular logs to track issue with activation of duplicate activities
  src/components/Activities/context/ActivityProvider.tsx
  src/components/GraphqlWrapper.tsx
  src/hooks/useLogging/types.ts
  src/hooks/useLogging/useLogging.ts
  src/services/graphql/apollo-client.ts
Labels: echoes/intent: unblock

#248 fix error in apollo graphql wrapper
  src/components/GraphqlWrapper.tsx
  src/services/graphql/apollo-client.ts
Labels: echoes/intent: unblock, echoes/impediment: dependencies
