Repository awell-health/hosted-pages, pull requests merged in 2024-10, with the labels that each got.

#276 add-sol-logging
  pages/api/sol/providers/index.ts
  src/utils/getAccessToken.ts
Labels: enhancement, Review effort [1-5]: 2, bug fix

#277 update logging
  pages/api/sol/providers/index.ts
  src/utils/getAccessToken.ts
Labels: enhancement, Review effort [1-5]: 2, bug fix

#278 feat(extension): add header to medication extraction review component
  src/components/Extension/ShellyExtension/actions/ReviewMedicationExtraction/ReviewMedicationExtraction.module.css
  src/components/Extension/ShellyExtension/actions/ReviewMedicationExtraction/ReviewMedicationExtraction.tsx
Labels: enhancement, echoes/intent: unblock, Review effort [1-5]: 3

#279 bump the version
  package.json
  yarn.lock
Labels: dependencies, Review effort [1-5]: 1

#280 bump the version of sol scheduling
  package.json
  yarn.lock
Labels: dependencies, Review effort [1-5]: 1

#281 release-sol-scheduling-2.21
  package.json
  yarn.lock
Labels: dependencies, Review effort [1-5]: 1

#282 bump(sol): 0.2.23
  package.json
  pages/api/sol/providers/[id]/availability.ts
  pages/api/sol/providers/index.ts
  yarn.lock
Labels: enhancement, Review effort [1-5]: 2, bug fix

#284 bump(sol): 0.3.0
  package.json
  yarn.lock
Labels: dependencies

#285 bump(sol): 0.3.1
  package.json
  pages/api/sol/providers/index.ts
  src/components/Extension/PrivateExtensions/actions/IntakeScheduling/IntakeScheduling.tsx
  src/components/Extension/PrivateExtensions/actions/IntakeScheduling/types.ts
  src/utils/logging.ts
  yarn.lock
Labels: enhancement, Review effort [1-5]: 3, bug fix

#287 fix the functions to wait to the result
  package.json
  pages/api/sol/providers/index.ts
  src/components/Extension/PrivateExtensions/actions/IntakeScheduling/IntakeScheduling.tsx
  src/components/Extension/PrivateExtensions/actions/IntakeScheduling/api.service.ts
  yarn.lock
Labels: enhancement, Review effort [1-5]: 3, bug fix

#288 release-sol-scheduling-0.3.8
  package.json
  yarn.lock
Labels: dependencies, Review effort [1-5]: 1

#289 feat: bump ui-library to latest version
  package.json
  yarn.lock
Labels: echoes/intent: throughput

#290 bump ui-kit version
  package.json
  yarn.lock
Labels: dependencies, Review effort [1-5]: 1

#292 rollback-ui-lib0.1.72
  package.json
  yarn.lock
Labels: dependencies, Review effort [1-5]: 1

#293 bump ui lib to 1.74
  package.json
  yarn.lock
Labels: enhancement, dependencies, Review effort [1-5]: 1

#294 release-sol-scheduling-3.10
  package.json
  yarn.lock
Labels: dependencies, Review effort [1-5]: 1

#296 bump ui-library to 0.1.78
  package.json
  yarn.lock
Labels: echoes/impediment: technical-debt, Review effort [1-5]: 1

#297 bump version of sol-scheduling & ui-kit
  package.json
  yarn.lock
Labels: Review effort [1-5]: 1
