Repository awell-health/hosted-pages, pull requests merged in 2025-05, with the labels that each got.

#350 Tsup-58-improve-readability-of-logs-in-hosted-sessions
  pages/api/log/index.ts
  pages/api/sol/appointments.ts
  pages/api/sol/providers/[id]/availability.ts
  pages/api/sol/providers/[id]/index.ts
  pages/api/sol/providers/index.ts
  pages/api/wp/lookup/providers/[siteId]/index.ts
  pages/index.tsx
  src/components/Activities/Activities.tsx
  src/components/Activities/ActivityFactory.tsx
  src/components/Activities/context/ActivityProvider.tsx
  src/components/Extension/CollectDataExtension/actions/RemoteSingleSelectAction/RemoteSingleSelectAction.tsx
  src/components/Extension/PrivateExtensions/actions/IntakeScheduling/api.service.ts
  src/components/Form/Form.tsx
  src/components/GraphqlWrapper.tsx
  src/hooks/useLogging/types.ts
  src/hooks/useLogging/useLogging.ts
  src/hooks/useMessage/useMessage.ts
  src/hooks/useSubmitChecklist/useSubmitChecklist.ts
  src/hooks/useSubmitForm/useSubmitForm.ts
  src/utils/logging.ts
Labels: Review effort 3/5

#346 Fix a race condition in AHP
  src/hooks/useSessionActivities/useSessionActivities.ts
Labels: Review effort 3/5

#351 bump-ui-lib-to-v0.1.100
  package.json
  yarn.lock
Labels: Review effort 1/5

#354 fix: reduce the chances of racing condition impacting form activities
  src/components/Form/Form.tsx
  src/hooks/useEvaluateFormRules/useEvaluateFormRules.ts
  src/hooks/useForm/useForm.ts
  src/hooks/useLogging/types.ts
Labels: Review effort 4/5
