Repository awell-health/hosted-pages, pull requests merged in 2025-02, with the labels that each got.

#334 bump sol-scheduling
  package.json
  yarn.lock
Labels: Review effort [1-5]: 1

#336 Bump ui library
  package.json
  yarn.lock
Labels: Review effort [1-5]: 1

#337 [ET-921] use image component to display SVG file
  pages/index.tsx
  pages/preview.tsx
Labels: Review effort [1-5]: 2

#338 ET-976-release-sol-scheduling-0.3.33
  package.json
  yarn.lock
Labels: Review effort 1/5

#339 feat(activities): allow filter by track_id or activity_id
  pages/api/startHostedActivitySessionViaHostedPagesLink/[hostedPagesLinkId].ts
  pages/api/startHostedPathwaySessionFromLink/[hostedPagesLinkId].ts
  pages/c/[hostedPagesLinkId].tsx
  pages/l/[hostedPagesLinkId].tsx
  src/components/Activities/Activities.tsx
  src/components/StartHostedActivitySessionFlow/StartHostedActivitySessionFlow.tsx
  src/components/StartHostedPathwaySessionFlow/StartHostedPathwaySessionFlow.tsx
  src/hooks/useSessionActivities/graphql/Activity.graphql
  src/hooks/useSessionActivities/useSessionActivities.ts
  src/types/generated/fragment-types.ts
  src/types/generated/types-orchestration.tsx
  types/StartHostedActivitySessionParams.ts
Labels: Review effort 4/5
